version: '2'

services:
  web:
    image: ssilvia9977/server3:latest
    environment:
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://database:5432/bikeDb
      - spring.datasource.username=bikeDb
      - spring.datasource.password=bikeDb
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
      - spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
      - spring.datasource.driver-class-name=org.postgresql.Driver 
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=bikeDb
      - POSTGRES_USER=bikeDb
      - POSTGRES_PASSWORD=bikeDb
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume: